FROM python:3.10

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1 \
  PYTHONUNBUFFERED 1 \
  PIP_NO_CACHE_DIR off \
  PIP_DISABLE_PIP_VERSION_CHECK on

COPY /fastapi_server/pyproject.toml /app/pyproject.toml
COPY /fastapi_server/poetry.lock /app/poetry.lock

RUN  curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python && \
  cd /usr/local/bin && \
  ln -s /opt/poetry/bin/poetry && \
  poetry config virtualenvs.create false

RUN poetry install --no-root

COPY /fastapi_server /app

EXPOSE 8080

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
