version: '3.8'

services:
  grpc-server:
    build:
      context: .
      dockerfile: Dockerfile.grpc_server
    restart: always
    ports:
      - 50051:50051

  
  fastapi-server:
    build:
        context: .
        dockerfile: Dockerfile.fastapi_server
    restart: always
    environment:
      - PORT=8000
    ports:
      - 8000:8000

  node-client:
    build:
      context: .
      dockerfile: Dockerfile.node_client
    restart: always
    ports:
      - 3000:3000

volumes:
  postgres-data: null
