version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  grpc-server:
    build:
      context: .
      dockerfile: Dockerfile.grpc_server
    restart: always
    ports:
      - 50051:50051
    depends_on:
      - postgres
    environment:
      - POSTGRES_URI=postgresql://postgres:postgres@postgres:5432/postgres

  
  fastapi-server:
    build:
        context: .
        dockerfile: Dockerfile.fastapi_server
    restart: always
    ports:
      - 8000:8080
    depends_on:
      - postgres
    environment:
      - POSTGRES_URI=postgresql://postgres:postgres@postgres:5432/postgres

volumes:
  postgres-data: null
